name: Publish package

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - run: yarn install
        name: Install Dependencies
      - run: yarn build
        name: Build Package
      - run: git config user.email "you@example.com" && git config user.name "Your Name"
        name: Configure Fake Git User
      - run: yarn publish --new-version ${GITHUB_REF##*/v} --access public
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
