name: Publish package

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: 12
      - run: yarn install
        name: Install Dependencies
      - run: yarn build
        name: Test Build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - run: yarn install
        name: Install Dependencies
      - run: yarn build
        name: Build Package
      - run: yarn publish --tag ${GITHUB_REF##*/v} --access public
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
