name: Publish package

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: 12
      - run: yarn install
        name: Install Dependencies
      - run: yarn build
        name: Test Build
